name: maryana
version: 2.1.152+152
publish_to: none
description: Mariannella Amazing Ecommerce App In Lebnanon
environment:
  sdk: '>=3.4.1 <4.0.0'




dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

dependencies:
  cupertino_icons: ^1.0.6
  lottie: ^3.1.2
  get: 4.6.6
  dio: ^4.0.6 
  flutter_animate: 4.5.0
  sliding_up_panel: 2.0.0+1
  google_sign_in: ^6.2.1
  photo_view: ^0.14.0
  widget_zoom:


  firebase_auth: any
  #  sentry_flutter:
  flutter_deep_linking: any
  uni_links: ^0.5.1
  video_player: ^2.8.1
  visibility_detector: 0.4.0+2
  typewritertext: 3.0.8
  firebase_database: any
  get_storage: 2.1.1
  firebase_app_check: any
  firebase_messaging: ^15.0.3
  carousel_slider: 5.0.0
  url_launcher: ^6.3.0
  delayed_widget: any
  flutter_rating_bar: any
  shorebird_code_push:

  restart_app:
  page_transition: any
  flutter_svg: any
  shared_preferences: 2.2.2
  awesome_snackbar_content: any
  awesome_notifications: ^0.9.3+1
  flutter_screenutil: ^5.9.3
  cached_network_image: any
  upgrader: any
  shimmer: any
  logger: ^1.1.0
  loading_animation_widget: ^1.2.1
  local_hero: any
  get_it: any
  avatar_glow: any
  flutter_spinkit: any
  percent_indicator: any
  pinput: any
  mobx: ^2.2.1
  flutter_mobx: any
  path_provider: 2.1.3
  google_fonts: any
  modal_bottom_sheet: any
  sign_in_with_apple: ^6.1.0
  image_picker: any
  geocoding: ^3.0.0
  geolocator: 12.0.0
  device_info_plus:
  google_api_headers:
  json_annotation:
  google_maps_flutter: 2.5.3
  share_plus:
  app_links:
  public_ip_address:
  image: ^3.0.1
  scrollable_positioned_list:
  smooth_page_indicator:
  googleapis:
  googleapis_auth:
  sentry_flutter:
  connectivity_plus:
  chewie:
  webview_flutter:

flutter:
  uses-material-design: true






  assets:
    - assets/images/
    - assets/images/cart/
    - assets/icons/
    - assets/images/splash/
    - assets/images/onboarding/
    - assets/images/forgot_password/
    - assets/images/home/
    - assets/images/product/
    - assets/images/profile/
    - shorebird.yaml
